{% set version = "0.26.0" %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: ccf3e2b9374792f88797a28ce82451faeae0136037cb8c8b56ba0a6c1a94fd69

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  license_family: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
