{% set version = "0.23.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: 30b6256bea0143caebd08256e0a605280afbbc5eef7ce692f84621eb232a9b31

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - clangdev              # [not osx]
    - llvmdev               # [not osx]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  license_family: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
