{% set version = "0.18.2" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: b176787e27da1f920b655bcd71b66c1569d241e2272bb9a4f6a64e6501c0cf2a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - clangdev              # [not osx]
    - llvmdev               # [not osx]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  license_family: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
