{% set version = "0.12.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: 7a3d0d94b6bffa00644a4afbc5952f87965f4723de3878b97ef8b7ebfd912477

build:
  number: 0

requirements:
  build:
    - rust
    - binutils              # [linux]
    - {{native}}binutils    # [win]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
