{% set version = "0.24.0" %}

package:
  name: bat
  version: {{ version }}

source:
  url: https://github.com/sharkdp/bat/archive/v{{ version }}.tar.gz
  sha256: 907554a9eff239f256ee8fe05a922aad84febe4fe10a499def72a4557e9eedfb

build:
  number: 1

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [unix]
    - {{ stdlib("c") }}                # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
  host:
    - clangdev              # [not osx]
    - llvmdev               # [not osx]

test:
  commands:
    - bat --help

about:
  home: https://github.com/sharkdp/bat
  license: MIT
  license_family: MIT
  summary: A cat(1) clone with syntax highlighting and Git integration
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - apcamargo
    - dbast
