travis:
  secure:
    BINSTAR_TOKEN: tzQAg0Ic/twa/eCUhs9+RnDcJCS5ddVVzJBLdUh1x+QO6fDDP/wHt6/uJTdhqPENw+FAbheacVJg/NDrSnltuTZYpMAxWIICVV+EUfjZGPumBRWJgZfiQLNE/x3kR2u1XlOl6ifFT6/T1axK7mGVjrIU4SEZ7gEZDD/F6eazLVaabX6OFDzJm1Ael3KS7YUdFBCHZ/o0UV0W1lEbWw66ZdsOIVcMklRZvkrtpWH/VR9PG0z234MctMvEGlXg3vQyTzsgtlDTs3/VzSdBnWU1F4hUTBzltbhxyUdrWkaUYW5JNcml97tBVIftbcWDo20Alz66uOr/AoJmfVHbi134h9YACPG1QmgnuOcYh972Hfz4myj7q0V7w3W9Oqs3Y8qzAxUXTXV2fbQZ+VePdx7HBZ0goLnv54ubsPYaSP0xvEGYE6L0gE/UdX45MVdsL750zkh0T5m5+ZxuIBlZLtKEOU1qMmydEdvEN2//K/833FtWk2Tkb2zJYMExaOrHs2fxhoVQcnBbkCfM5TeWtEfgM3oWxtV25taHmZzJzUgdkdGa9oPg23BQaXFGQYAKvqYrwSdXsipPWu7ZRzldAJf1MzAP5DlYCMLl0XUXFIVEJ7yCfKuWJhFDz6KI7X1+XiI/cj91lzSaV0ft6MJojyl0JJQxBW6R3TuCE8kwkMSQDLg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
conda_forge_output_validation: false
